## Sentiment analysis of different Crypto-Currencies using Social-media Data

<hr>

### Team information
**1. Harsh Bamotra (AC-1216)** <br>
**2. Pratham Sharma (AC-1232)** <br>

Teacher       : **Prof. Vibha Gaur** <br>
Course        : **BSc. (H) Computer Science** <br>
Semester/Year : **3rd / 2nd Year** <br>
College       : **Acharya Narendra Dev College** <br>

In [1]:
import numpy as np
import pandas as pd
import re 
from textblob import TextBlob

In [2]:
mainDF = pd.read_csv("Tweets-Dogecoin.csv")
mainDF.head()

,date,time,timezone,username,name,tweet,language,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,video,thumbnail,reply_to
0,20-04-2021,17:57:09,530,sunnyepposo,congrats ‚ú®,I invested $16k a couple of weeks ago when a l...,en,None,['http://discord.gg/5zwNm6Kn9v'],['https://pbs.twimg.com/media/EzaspZBVEAMHmZE....,0,0,0,"['dogeday420', 'dogeday', 'doge420', 'dogecoin']",['doge'],1,https://pbs.twimg.com/media/EzaspZBVEAMHmZE.jpg,None
1,20-04-2021,17:57:07,530,pickndng,andrea || busy sa exams at pts kunoüçÄ‚ú®,Bought in for $16k. My #dogecoin will make me ...,en,None,['http://discord.gg/5zwNm6Kn9v'],['https://pbs.twimg.com/media/EzaspdbVgAgSD_D....,0,0,0,"['dogecoin', 'doge', 'dogeday']",None,1,https://pbs.twimg.com/media/EzaspdbVgAgSD_D.jpg,None
2,20-04-2021,17:57:07,530,s4y4n9_semu4,#SayangiSemesta,I invested $16k a couple of weeks ago when a l...,en,None,['http://discord.gg/5zwNm6Kn9v'],['https://pbs.twimg.com/media/EzaspfMVoAAmNIi....,0,0,0,"['dogeday420', 'dogeday', 'doge420', 'dogecoin']",['doge'],1,https://pbs.twimg.com/media/EzaspfMVoAAmNIi.jpg,None
3,20-04-2021,17:57:06,530,dogecoinsky,dogecoinsky,"looking back in 2010/11, BTC had low value, hi...",en,None,None,None,0,0,0,"['dogecoin', 'dogeday', 'dogecoinsky']",None,0,NaN,None
4,20-04-2021,17:57:04,530,dogeman0401,jay,Looks like the hype of today isn‚Äôt coming to f...,en,None,None,None,0,0,0,"['doge420', 'dogeday420', 'doge', 'dogecoin']",None,0,NaN,None

In [3]:
mainDF = mainDF.loc[: , ["date" , "time" , "timezone" , "tweet"]]   #removing extra information 
mainDF.head()

,date,time,timezone,tweet
0,20-04-2021,17:57:09,530,I invested $16k a couple of weeks ago when a l...
1,20-04-2021,17:57:07,530,Bought in for $16k. My #dogecoin will make me ...
2,20-04-2021,17:57:07,530,I invested $16k a couple of weeks ago when a l...
3,20-04-2021,17:57:06,530,"looking back in 2010/11, BTC had low value, hi..."
4,20-04-2021,17:57:04,530,Looks like the hype of today isn‚Äôt coming to f...

In [4]:
def cleanTwt(twt):
    twt = re.sub("#bitcoin", 'bitcoin', twt)   # removes the '#' from bitcoin
    twt = re.sub("#Bitcoin", 'Bitcoin', twt)   # removes the '#' from Bitcoin
    twt = re.sub('#[A-Za-z0-9]+', '', twt)     # removes any string with a '#'
    twt = re.sub('\\n', '', twt)               # removes the '\n' string
    twt = re.sub('https:\/\/\S+', '', twt)     # removes any hyperlinks
    return twt

In [5]:
mainDF["Cleaned"] = mainDF["tweet"].apply(cleanTwt)
mainDF.head()

,date,time,timezone,tweet,Cleaned
0,20-04-2021,17:57:09,530,I invested $16k a couple of weeks ago when a l...,I invested $16k a couple of weeks ago when a l...
1,20-04-2021,17:57:07,530,Bought in for $16k. My #dogecoin will make me ...,Bought in for $16k. My will make me a million...
2,20-04-2021,17:57:07,530,I invested $16k a couple of weeks ago when a l...,I invested $16k a couple of weeks ago when a l...
3,20-04-2021,17:57:06,530,"looking back in 2010/11, BTC had low value, hi...","looking back in 2010/11, BTC had low value, hi..."
4,20-04-2021,17:57:04,530,Looks like the hype of today isn‚Äôt coming to f...,Looks like the hype of today isn‚Äôt coming to f...

In [6]:
def getSubjectivity(tweet):
   return TextBlob(tweet).sentiment.subjectivity

def getPolarity(tweet):
   return  TextBlob(tweet).sentiment.polarity

In [7]:
mainDF['Subjectivity'] = mainDF['Cleaned'].apply(getSubjectivity)
mainDF['Polarity'] = mainDF['Cleaned'].apply(getPolarity)
mainDF

,date,time,timezone,tweet,Cleaned,Subjectivity,Polarity
0,20-04-2021,17:57:09,530,I invested $16k a couple of weeks ago when a l...,I invested $16k a couple of weeks ago when a l...,0.428571,0.214286
1,20-04-2021,17:57:07,530,Bought in for $16k. My #dogecoin will make me ...,Bought in for $16k. My will make me a million...,0.533333,0.000000
2,20-04-2021,17:57:07,530,I invested $16k a couple of weeks ago when a l...,I invested $16k a couple of weeks ago when a l...,0.428571,0.214286
3,20-04-2021,17:57:06,530,"looking back in 2010/11, BTC had low value, hi...","looking back in 2010/11, BTC had low value, hi...",0.340000,0.117143
4,20-04-2021,17:57:04,530,Looks like the hype of today isn‚Äôt coming to f...,Looks like the hype of today isn‚Äôt coming to f...,0.000000,0.000000
...,...,...,...,...,...,...,...
250004,16-04-2021,06:01:13,530,#dogecoin reaches $0.20! https://t.co/yBkUBC3xRI,reaches $0.20!,0.000000,0.000000
250005,16-04-2021,06:01:12,530,#dogecoin #LATOKEN https://t.co/CiR47MT9Qz,,0.000000,0.000000
250006,16-04-2021,06:01:12,530,#dogecoin community is unlike any on the plane...,community is unlike any on the planet! That‚Äôs...,0.000000,0.000000
250007,16-04-2021,06:01:11,530,Doge Prediction: Up #dogecoin,Doge Prediction: Up,0.000000,0.000000
250008,16-04-2021,06:01:10,530,@BeefSupreme1776 Did you read the article? To ...,@BeefSupreme1776 Did you read the article? To ...,1.000000,0.000000

In [8]:
def getAnalysis(score):
 if score < 0:
  return 'Negative'
 elif score == 0:
  return 'Neutral'
 else:
  return 'Positive'

In [9]:
mainDF["Analysis"] = mainDF["Polarity"].apply(getAnalysis)
mainDF

,date,time,timezone,tweet,Cleaned,Subjectivity,Polarity,Analysis
0,20-04-2021,17:57:09,530,I invested $16k a couple of weeks ago when a l...,I invested $16k a couple of weeks ago when a l...,0.428571,0.214286,Positive
1,20-04-2021,17:57:07,530,Bought in for $16k. My #dogecoin will make me ...,Bought in for $16k. My will make me a million...,0.533333,0.000000,Neutral
2,20-04-2021,17:57:07,530,I invested $16k a couple of weeks ago when a l...,I invested $16k a couple of weeks ago when a l...,0.428571,0.214286,Positive
3,20-04-2021,17:57:06,530,"looking back in 2010/11, BTC had low value, hi...","looking back in 2010/11, BTC had low value, hi...",0.340000,0.117143,Positive
4,20-04-2021,17:57:04,530,Looks like the hype of today isn‚Äôt coming to f...,Looks like the hype of today isn‚Äôt coming to f...,0.000000,0.000000,Neutral
...,...,...,...,...,...,...,...,...
250004,16-04-2021,06:01:13,530,#dogecoin reaches $0.20! https://t.co/yBkUBC3xRI,reaches $0.20!,0.000000,0.000000,Neutral
250005,16-04-2021,06:01:12,530,#dogecoin #LATOKEN https://t.co/CiR47MT9Qz,,0.000000,0.000000,Neutral
250006,16-04-2021,06:01:12,530,#dogecoin community is unlike any on the plane...,community is unlike any on the planet! That‚Äôs...,0.000000,0.000000,Neutral
250007,16-04-2021,06:01:11,530,Doge Prediction: Up #dogecoin,Doge Prediction: Up,0.000000,0.000000,Neutral
250008,16-04-2021,06:01:10,530,@BeefSupreme1776 Did you read the article? To ...,@BeefSupreme1776 Did you read the article? To ...,1.000000,0.000000,Neutral

In [10]:
mainDF['Analysis'].value_counts()

Neutral     148806
Positive     78221
Negative     22982
Name: Analysis, dtype: int64